version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  # Skip examples directory (demo code, not production)
  exclude-dirs:
    - ^examples$

linters:
  default: standard

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Println
        - (net/http.ResponseWriter).Write
        - (*net/http.Request).ParseForm
        - (*github.com/gorilla/sessions.Session).Save
        - (*bytes.Buffer).ReadFrom
        - io.Copy
        - (io.Closer).Close
        - os.Setenv
        - (*encoding/json.Encoder).Encode

    staticcheck:
      # Disable some noisy checks for legacy code
      checks:
        - "all"
        - "-ST1000"  # Package comments
        - "-ST1003"  # Naming conventions (clientId vs clientID)
        - "-ST1005"  # Error string capitalization
        - "-S1011"   # Loop simplification suggestions

issues:
  exclude-rules:
    # Ignore unchecked errors in all tests
    - path: _test\.go
      linters:
        - errcheck

    # Ignore ineffassign in providers (legacy code)
    - path: providers/
      linters:
        - ineffassign

  max-issues-per-linter: 50
  max-same-issues: 10
