on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

name: ci

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'
    - name: Install golangci-lint v2
      run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.7.2
    - name: Run golangci-lint
      run: golangci-lint run --timeout=5m

  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.25.x, 1.26.x ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Format
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.25.x'
    - name: Check go mod tidy
      run: go mod tidy && git diff --exit-code go.mod go.sum
      if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.25.x'
    - name: Test
      run: go test -race ./...
